const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "0770127991";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,077012799a";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_00_03_02_11_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTUyLFxuICAgICAgICA4MyxcbiAgICAgICAgMjAyLFxuICAgICAgICAxOTgsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTYsXG4gICAgICAgIDUxLFxuICAgICAgICAyMDMsXG4gICAgICAgIDMwLFxuICAgICAgICA4MSxcbiAgICAgICAgMTQ4LFxuICAgICAgICAzNyxcbiAgICAgICAgNTUsXG4gICAgICAgIDI5LFxuICAgICAgICAxMjUsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMjM0LFxuICAgICAgICAxNzIsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMTk1LFxuICAgICAgICAxODQsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTM0LFxuICAgICAgICAyMzEsXG4gICAgICAgIDE2MyxcbiAgICAgICAgODMsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTE2LFxuICAgICAgICAxNzksXG4gICAgICAgIDIzMSxcbiAgICAgICAgMjM4LFxuICAgICAgICA3OVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA5NixcbiAgICAgICAgMjE4LFxuICAgICAgICAxMSxcbiAgICAgICAgMTczLFxuICAgICAgICA2NyxcbiAgICAgICAgNDgsXG4gICAgICAgIDEzMixcbiAgICAgICAgMjA1LFxuICAgICAgICAxNTEsXG4gICAgICAgIDE3LFxuICAgICAgICAyNDEsXG4gICAgICAgIDE0LFxuICAgICAgICAyMDMsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTc3LFxuICAgICAgICAyMDUsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTA1LFxuICAgICAgICAyMzcsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMjQxLFxuICAgICAgICAxNDcsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMjUzLFxuICAgICAgICAyMTEsXG4gICAgICAgIDQ0LFxuICAgICAgICAyMDEsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTQ0LFxuICAgICAgICAxNTcsXG4gICAgICAgIDI0LFxuICAgICAgICAxMjVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2LFxuICAgICAgICAxNjcsXG4gICAgICAgIDcxLFxuICAgICAgICAyMjMsXG4gICAgICAgIDEyMixcbiAgICAgICAgMTksXG4gICAgICAgIDU5LFxuICAgICAgICAxNDcsXG4gICAgICAgIDMyLFxuICAgICAgICAxNDUsXG4gICAgICAgIDQ4LFxuICAgICAgICAyMzMsXG4gICAgICAgIDExMSxcbiAgICAgICAgOTksXG4gICAgICAgIDMyLFxuICAgICAgICA3NyxcbiAgICAgICAgMjEsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMTg4LFxuICAgICAgICA0LFxuICAgICAgICAxMzIsXG4gICAgICAgIDE1OSxcbiAgICAgICAgOCxcbiAgICAgICAgNTIsXG4gICAgICAgIDgzLFxuICAgICAgICA4MixcbiAgICAgICAgNzMsXG4gICAgICAgIDExLFxuICAgICAgICAxODksXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTEzLFxuICAgICAgICA3N1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4LFxuICAgICAgICA0MyxcbiAgICAgICAgMjExLFxuICAgICAgICAxMjksXG4gICAgICAgIDU2LFxuICAgICAgICAxODksXG4gICAgICAgIDIxMCxcbiAgICAgICAgNTcsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMjM2LFxuICAgICAgICAxMixcbiAgICAgICAgMzYsXG4gICAgICAgIDQ1LFxuICAgICAgICA1LFxuICAgICAgICA3MCxcbiAgICAgICAgMjQwLFxuICAgICAgICAyMDMsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTE4LFxuICAgICAgICAxOTcsXG4gICAgICAgIDcyLFxuICAgICAgICAyLFxuICAgICAgICA0OSxcbiAgICAgICAgOCxcbiAgICAgICAgMjE4LFxuICAgICAgICAzNSxcbiAgICAgICAgMjQxLFxuICAgICAgICAxMjEsXG4gICAgICAgIDk5LFxuICAgICAgICA0LFxuICAgICAgICAyMzUsXG4gICAgICAgIDQzXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNTIsXG4gICAgICAgIDM5LFxuICAgICAgICAxNDAsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxNyxcbiAgICAgICAgNSxcbiAgICAgICAgNjAsXG4gICAgICAgIDIxOSxcbiAgICAgICAgNTQsXG4gICAgICAgIDIxLFxuICAgICAgICAyNixcbiAgICAgICAgOTIsXG4gICAgICAgIDEyNCxcbiAgICAgICAgNzAsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTczLFxuICAgICAgICAyNixcbiAgICAgICAgMTY4LFxuICAgICAgICAyMCxcbiAgICAgICAgNDEsXG4gICAgICAgIDE0MSxcbiAgICAgICAgNDgsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTk1LFxuICAgICAgICAyNTUsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMzIsXG4gICAgICAgIDY1LFxuICAgICAgICAxOTAsXG4gICAgICAgIDIyLFxuICAgICAgICA3M1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDgsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTUyLFxuICAgICAgICA4NixcbiAgICAgICAgMTIsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMjMwLFxuICAgICAgICAxNDUsXG4gICAgICAgIDM3LFxuICAgICAgICA5NyxcbiAgICAgICAgMzgsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxOTcsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTgsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMjMwLFxuICAgICAgICAxMDIsXG4gICAgICAgIDQ3LFxuICAgICAgICAzMixcbiAgICAgICAgNDUsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTgwLFxuICAgICAgICAxMzgsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTcwLFxuICAgICAgICAxMTIsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTc5LFxuICAgICAgICAyNDYsXG4gICAgICAgIDY1XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE2OCxcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICA5OSxcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgMjQzLFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICA5LFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDk3LFxuICAgICAgICAgIDE1MSxcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgMTg1LFxuICAgICAgICAgIDQ1LFxuICAgICAgICAgIDE4NCxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDEwOCxcbiAgICAgICAgICA4MyxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgMzYsXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgODUsXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgMTI1XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDEwMyxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgMjU0LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDEyMixcbiAgICAgICAgICAxNzUsXG4gICAgICAgICAgNTAsXG4gICAgICAgICAgMTQ2LFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICAxNixcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICAxLFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICAyMTAsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDI1MCxcbiAgICAgICAgICAxMyxcbiAgICAgICAgICA5MlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDkyLFxuICAgICAgICAyMjQsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTMzLFxuICAgICAgICAxNjMsXG4gICAgICAgIDE0OCxcbiAgICAgICAgNzcsXG4gICAgICAgIDIxMixcbiAgICAgICAgMjM1LFxuICAgICAgICA1MyxcbiAgICAgICAgMjA0LFxuICAgICAgICAxNTgsXG4gICAgICAgIDkxLFxuICAgICAgICAxNTEsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTkyLFxuICAgICAgICAzOCxcbiAgICAgICAgNTUsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTMsXG4gICAgICAgIDcwLFxuICAgICAgICA4NSxcbiAgICAgICAgNTIsXG4gICAgICAgIDEyNCxcbiAgICAgICAgNzAsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTY0LFxuICAgICAgICAyMjMsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMjM2LFxuICAgICAgICA0NyxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxMyxcbiAgICAgICAgODQsXG4gICAgICAgIDkzLFxuICAgICAgICAyMSxcbiAgICAgICAgMzYsXG4gICAgICAgIDI0OSxcbiAgICAgICAgODIsXG4gICAgICAgIDE4MCxcbiAgICAgICAgMTQxLFxuICAgICAgICAxMjYsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMjEyLFxuICAgICAgICAxNDksXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTA3LFxuICAgICAgICAxODcsXG4gICAgICAgIDE4MixcbiAgICAgICAgMjUwLFxuICAgICAgICA3NyxcbiAgICAgICAgNzksXG4gICAgICAgIDYyLFxuICAgICAgICAyMjMsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMjA3LFxuICAgICAgICA1MyxcbiAgICAgICAgMTYxLFxuICAgICAgICA5OCxcbiAgICAgICAgMjQ3LFxuICAgICAgICAyMDksXG4gICAgICAgIDE2MyxcbiAgICAgICAgMjEyLFxuICAgICAgICA2XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxMDEsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiNnhKVGEyMjBlRGZ6NGdzV0J0Ym5QSkx1bml5TExXYzJFWVJQQkEzU25Cbz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMTI3MDMwMDI2NjNAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjJBOTBFMDBCRDE3MzVEQzAyN0IyXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTc3MDc2ODIxNlxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIxMjcwMzAwMjY2M0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiMkFGMjFBMjJFRTVCMjMzOTZEMjNcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzcwNzY4MjE3XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjEyNzAzMDAyNjYzQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIyQTRDRTE4OTdBRkNCMjFEOTcxNVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3NzA3NjgyMThcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiM0kwMXJrUnlRSzY3STFKTm5LT09CZ1wiLFxuICBcInBob25lSWRcIjogXCI0NzdkMmM2YS03ZDA3LTRmMDEtODkwOS1mZDNkNzZkOTQ1MTJcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjQsXG4gICAgICAyNTUsXG4gICAgICAxMzAsXG4gICAgICA3NyxcbiAgICAgIDIzMCxcbiAgICAgIDE0OSxcbiAgICAgIDEzMixcbiAgICAgIDIyOSxcbiAgICAgIDE3OSxcbiAgICAgIDE5OCxcbiAgICAgIDksXG4gICAgICAyMDIsXG4gICAgICA0MCxcbiAgICAgIDk3LFxuICAgICAgMjUyLFxuICAgICAgMjUwLFxuICAgICAgODEsXG4gICAgICA1MyxcbiAgICAgIDIxNyxcbiAgICAgIDU2XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogZmFsc2UsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyNDksXG4gICAgICA1MSxcbiAgICAgIDI1MyxcbiAgICAgIDkxLFxuICAgICAgMTcwLFxuICAgICAgMjUzLFxuICAgICAgNTcsXG4gICAgICA2OCxcbiAgICAgIDIwOCxcbiAgICAgIDgsXG4gICAgICAxMTMsXG4gICAgICAxMjUsXG4gICAgICAxOTcsXG4gICAgICAyMTcsXG4gICAgICA2MixcbiAgICAgIDg4LFxuICAgICAgNTEsXG4gICAgICAxOTYsXG4gICAgICAxMzEsXG4gICAgICAyMzVcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNQWGVzODRMRU5LT3I4d0dHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIjJWak9rcGhQTXY1MENqRGsvdVVQb1NXRnQ2V1ZUc0xtVlorRDhVdXBoa2s9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwidnIzSitqZ0pPbEFhU2NmajVqbGg2L25aZHBqZG8zNHBFRmFWVWhVdFc3Sm15cW9paldsMm5WeithaUJHd3lNVnhWRUxVUjlOblp3QldHMDF0U0tYaEE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiblBNNEtsQjM4RHFxRG54V3lIb3hKeVVjeUlFL2pRWEk4ZEp1ODNJUnlBYzJmUC9vZnJlSnlYMHlDMkI3Q3Q1WlNIVENBTU9GS3ZreWpTYmhTaXJUQ3c9PVwiXG4gIH0sXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMTI3MDMwMDI2NjM6MkBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcInZhc3RvXCIsXG4gICAgXCJsaWRcIjogXCIyNDk3ODc0MTI2ODA4NDA6MkBsaWRcIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIxMjcwMzAwMjY2MzoyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDUwLFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMTAsXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDEzMyxcbiAgICAgICAgICAxODMsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDE0OSxcbiAgICAgICAgICA3OCxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMjQxLFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgNzNcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcInNtYmlcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTc3MDc2ODIxNSxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUV5YlwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRXliLmpzb24iOiAie1wia2V5RGF0YVwiOlwiemRxNFRkcWtUU2JwdTh1TGVpN2dSYkpXLzhhNENpSFBqZEZnYTE4ZzVYYz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjozMTE3MjE1NjA1LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMSwwXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NzA3NjgyMTUwOTBcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "public",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
